motd:
  # Первая строка MOTD
  line1: "             &#FB0000-&#FB0A00-&#FB1400-&#FC1E00-&#FC2800-&#FC3200-&#FC3C00- &#FD4600V&#FD5000M&#FD5B00O&#FD6500T&#FD6F00D &#FE7900-&#FE8300-&#FE8D00-&#FE9700-&#FFA100-&#FFAB00-&#FFB500-"
  # Вторая строка MOTD
  line2: "                &aMOTD для сервера!"

# Настройки сообщений плагина
messages:
  # Сообщение при неверном использовании команды
  help-messages: "&cИспользование: /vmotd reload"
  # Сообщение при успешной перезагрузке
  reload-messages: "&aКонфигурация успешно перезагружена!"
  # Сообщение если у игрока нет прав
  no-permission: "&cУ вас нет прав для выполнения этой команды!"